### ISSUE TITLE
Reservoir State Matrix

### ISSUE THREAD

**Issue by mapmen** [stevenabreu7/handson_reservoir#1]
Hi, I'm trying to implement a physical Reservoir Computer model using PEDOT fibers. Your paper ("Hands on Reservoir computing....") is of great help, but I'm a little confused about the step of collecting the reservoir states.

On this link (http://www.scholarpedia.org/article/Echo_state_network), about Echo State Networks, the author (Herbert Jaeger) states that in order to do the linear regression step, we need the extended system state z(n) = [x(n);u(n)], which is the concatenation of the reservoir states and the input sequences. Comparing your work with the definition from Jaeger, both look similar, except on the reservoir state matrix, which in you work is only composed of the reservoir states, but not the input sequences as well.

Can you explain to me why is there a difference? Thanks in advance and great work :)

**Comment by stevenabreu7** [comment]
Hi there, thanks for reaching out. Either way is fine, really. If you think about this as a diagram, my implementation considers only the case where `u(n) → x(n) → y(n)`, and the ESN equations consider the case where you have additional "skip connections" from the input to the output, i.e.:
```
u(n) ---> x(n) ---> y(n)
   \                /
    ----------------
```

I chose to not include the direct connections from `u(n)` to `y(n)` because in physical reservoir computing, we typically care about the computational power of the reservoir (i.e., `x(n)`), and the additional skip connection does not go through the physical reservoir at all (assuming you implement the readout on an external computer). 

However, the performance of your system should be better (or equal) if you include `u(t)` in your system states. So if you care about the performance, then you should go for that (and of course, make it clear what it is that you're reporting).

**Comment by mapmen** [comment]
Hey @stevenabreu7 , thanks for the response. Sorry for taking too long to get back at you. This will help me a lot during my last months of Ph.D.  Thanks again for the help :)
